package com.larsons.engine.watch.world;

import com.larsons.engine.watch.render.FloraMesher;
import com.larsons.engine.watch.render.Mesh;
import com.larsons.engine.watch.render.TerrainMesher;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Which chunks exist, at what detail, and the workers that build them.
 *
 * <h2>Nothing is built on the frame that wants it</h2>
 *
 * <p>Generating a chunk is a thousand height samples, each of them eight noise
 * fields deep, plus the flora and the meshing — a few milliseconds, which is
 * most of a frame. Doing that while a frame waits is exactly the stutter a
 * streaming world exists to remove. So a frame says where the camera is, this
 * queues whatever is missing <b>nearest first</b> on a small pool of daemon
 * workers, and the frame draws what has arrived. What has not is a piece of
 * ground that appears a moment later at the edge of the view, which is what
 * every game of this shape does.
 *
 * <h2>Detail follows distance</h2>
 *
 * <p>A chunk's {@linkplain WatchChunk#lod() level of detail} is decided by how
 * far it is from the camera, and changing it is a re-mesh, not a re-generation
 * — the heightfield is the same data at every level. So walking toward a
 * hillside sharpens it for the price of the triangles, not the noise.
 *
 * <p>Grass is the exception that proves the rule: it exists only inside
 * {@link #grassRadius()} chunks, and those few meshes are rebuilt on a slow
 * cadence with the wind field advanced, which is how a meadow sways without
 * costing a single operation on a normal frame.
 *
 * <h2>Threads</h2>
 *
 * <p>{@code min(6, cores − 1)} of them, named {@code watch-chunk-N}, daemons so
 * a stuck build can never keep the game open. Each one builds a chunk to
 * completion and publishes it in one write to a concurrent map; nothing mutates
 * a published chunk except a re-mesh, which builds new meshes off to the side
 * and swaps them in with a single call.
 */
public final class ChunkStreamer implements AutoCloseable {

    /** How many chunks out the world is generated by default. */
    public static final int DEFAULT_VIEW_RADIUS = 10;

    /** How many chunks out the finest detail — and the grass — reaches. */
    public static final int DEFAULT_DETAIL_RADIUS = 2;

    /** How far past the view radius a chunk is kept before being thrown away. */
    private static final int EVICT_MARGIN = 3;

    /** How long between rebuilds of the near grass, in seconds. */
    private static final double GRASS_PERIOD = 2.2;

    private final TerrainField field;
    private final Flora flora;
    private final GrassField grassField;

    private final Map<Long, WatchChunk> loaded = new ConcurrentHashMap<>();
    private final Map<Long, Boolean> building = new ConcurrentHashMap<>();
    private final AtomicLong revisions = new AtomicLong(1);
    private final AtomicInteger inFlight = new AtomicInteger();

    private ExecutorService workers;
    private final int workerCount;
    private final int maxInFlight;

    private int viewRadius = DEFAULT_VIEW_RADIUS;
    private int detailRadius = DEFAULT_DETAIL_RADIUS;
    private int grassRadius = 1;
    private double grassClock;
    private double grassRebuiltAt = -GRASS_PERIOD;
    private long generated;

    public ChunkStreamer(long seed) {
        this(new TerrainField(seed));
    }

    public ChunkStreamer(TerrainField field) {
        this.field = field;
        this.flora = new Flora(field.seed(), field);
        this.grassField = new GrassField(field.seed());
        this.workerCount = Math.max(1, Math.min(6, Runtime.getRuntime().availableProcessors() - 1));
        this.maxInFlight = workerCount * 3;
    }

    /** The generator underneath — what the physics asks for ground it cannot see. */
    public TerrainField field() { return field; }

    /** The grass field, so the renderer can ask how long a blade is at a point. */
    public GrassField grassField() { return grassField; }

    /** How many chunks out the world is generated. */
    public int viewRadius() { return viewRadius; }

    /**
     * Set how far the world is generated, in chunks. A backend with a depth
     * buffer can afford far more than one painting back to front, so the scene
     * sets this from what it found rather than from a constant.
     */
    public void setViewRadius(int chunks) {
        this.viewRadius = Math.max(1, Math.min(48, chunks));
    }

    public int detailRadius() { return detailRadius; }

    public void setDetailRadius(int chunks) {
        this.detailRadius = Math.max(0, Math.min(viewRadius, chunks));
    }

    /** How many chunks out individual blades of grass are built. */
    public int grassRadius() { return grassRadius; }

    public void setGrassRadius(int chunks) {
        this.grassRadius = Math.max(0, Math.min(6, chunks));
    }

    /** How many chunks have been generated since this streamer started. */
    public long generatedCount() { return generated; }

    /** How many chunks are in memory. */
    public int loadedCount() { return loaded.size(); }

    /** How many builds are queued or running. */
    public int pending() { return inFlight.get(); }

    /** Every chunk currently in memory. */
    public Collection<WatchChunk> chunks() { return loaded.values(); }

    /** The chunk at a chunk coordinate, or {@code null} if it is not built yet. */
    public WatchChunk chunk(int cx, int cy) { return loaded.get(WatchChunk.key(cx, cy)); }

    /** The chunk containing a world position, or {@code null}. */
    public WatchChunk chunkAt(double x, double y) {
        return chunk(WatchChunk.chunkOf(x), WatchChunk.chunkOf(y));
    }

    /**
     * The ground's height at a world position.
     *
     * <p>From the chunk when there is one — a bilinear read of four samples,
     * which is what the triangles the player can see were built from, so they
     * stand on the ground rather than a few centimetres above or below it. When
     * there is not, straight from the generator: slower, exact, and never
     * absent, which is what a player who has just been teleported needs.
     */
    public double groundAt(double x, double y) {
        WatchChunk chunk = chunkAt(x, y);
        return chunk != null ? chunk.groundAt(x, y) : field.heightAt(x, y);
    }

    /** The biome at a world position, from the chunk when there is one. */
    public WatchBiome biomeAt(double x, double y) {
        WatchChunk chunk = chunkAt(x, y);
        return chunk != null ? chunk.biomeAtWorld(x, y) : field.biomeAt(x, y);
    }

    /** Whether a world position is under water. */
    public boolean underwater(double x, double y) {
        return groundAt(x, y) < TerrainField.WATER_LEVEL;
    }

    /**
     * Keep the world around a point loaded.
     *
     * <p>Called once a frame with the camera's position. Queues what is
     * missing, re-meshes what has changed detail, and drops what has been
     * walked away from — all of it bounded, so no single call can cost a frame.
     *
     * @param dt seconds since the last call, for the grass's own clock
     */
    public void update(double centreX, double centreY, double dt) {
        grassClock += dt;
        int ccx = WatchChunk.chunkOf(centreX);
        int ccy = WatchChunk.chunkOf(centreY);

        evictBeyond(ccx, ccy);

        boolean grassDue = grassClock - grassRebuiltAt >= GRASS_PERIOD;
        if (grassDue) grassRebuiltAt = grassClock;

        // Nearest first: the chunk under the player's feet matters more than
        // the one at the horizon, and a queue that does not say so fills the
        // view from the outside in.
        List<int[]> wanted = ring(ccx, ccy, viewRadius);
        for (int[] at : wanted) {
            if (inFlight.get() >= maxInFlight) break;
            long key = WatchChunk.key(at[0], at[1]);
            WatchChunk chunk = loaded.get(key);
            int lod = lodFor(at[0] - ccx, at[1] - ccy);
            if (chunk == null) {
                queueBuild(at[0], at[1], lod);
            } else if (chunk.lod() != lod) {
                queueMesh(chunk, lod, grassDue);
            } else if (grassDue && lod == 0 && withinGrass(at[0] - ccx, at[1] - ccy)) {
                queueMesh(chunk, lod, true);
            }
        }
    }

    /**
     * Build everything within a radius and wait for it — for tests, for a
     * screenshot, and for the moment a save is loaded and the player should not
     * see the world assemble itself around them.
     */
    public void loadNow(double centreX, double centreY, int radius) {
        int ccx = WatchChunk.chunkOf(centreX);
        int ccy = WatchChunk.chunkOf(centreY);
        for (int[] at : ring(ccx, ccy, radius)) {
            long key = WatchChunk.key(at[0], at[1]);
            if (loaded.containsKey(key)) continue;
            int lod = lodFor(at[0] - ccx, at[1] - ccy);
            WatchChunk chunk = WatchChunk.generate(field, flora, at[0], at[1],
                    revisions.getAndIncrement());
            // The same grass gate the streaming path uses. Passing `true` here
            // put individual blades on every chunk in the ring rather than on
            // the near few, which is most of a frame's triangles and made any
            // measurement taken through this method wrong about the game.
            mesh(chunk, lod, lod == 0 && withinGrass(at[0] - ccx, at[1] - ccy));
            loaded.put(key, chunk);
            generated++;
        }
    }

    private boolean withinGrass(int dx, int dy) {
        return Math.max(Math.abs(dx), Math.abs(dy)) <= grassRadius;
    }

    /** The detail a chunk this far from the camera is drawn at. */
    private int lodFor(int dx, int dy) {
        int distance = Math.max(Math.abs(dx), Math.abs(dy));
        if (distance <= detailRadius) return 0;
        if (distance <= detailRadius * 2 + 1) return 1;
        if (distance <= detailRadius * 4 + 3) return 2;
        return WatchChunk.MAX_LOD;
    }

    /** Chunk coordinates within a radius of a centre, nearest first. */
    private static List<int[]> ring(int ccx, int ccy, int radius) {
        List<int[]> out = new ArrayList<>((radius * 2 + 1) * (radius * 2 + 1));
        for (int dy = -radius; dy <= radius; dy++) {
            for (int dx = -radius; dx <= radius; dx++) {
                out.add(new int[]{ccx + dx, ccy + dy});
            }
        }
        out.sort(Comparator.comparingInt(at -> {
            int dx = at[0] - ccx, dy = at[1] - ccy;
            return dx * dx + dy * dy;
        }));
        return out;
    }

    private void evictBeyond(int ccx, int ccy) {
        int limit = viewRadius + EVICT_MARGIN;
        loaded.keySet().removeIf(key -> {
            int cx = (int) (key >> 32);
            int cy = (int) (key & 0xFFFFFFFFL);
            return Math.max(Math.abs(cx - ccx), Math.abs(cy - ccy)) > limit;
        });
    }

    private void queueBuild(int cx, int cy, int lod) {
        long key = WatchChunk.key(cx, cy);
        if (building.putIfAbsent(key, Boolean.TRUE) != null) return;
        inFlight.incrementAndGet();
        submit(() -> {
            try {
                WatchChunk chunk = WatchChunk.generate(field, flora, cx, cy,
                        revisions.getAndIncrement());
                mesh(chunk, lod, lod == 0);
                loaded.put(key, chunk);
                generated++;
            } finally {
                building.remove(key);
                inFlight.decrementAndGet();
            }
        });
    }

    private void queueMesh(WatchChunk chunk, int lod, boolean withGrass) {
        long key = chunk.key();
        if (building.putIfAbsent(key, Boolean.TRUE) != null) return;
        inFlight.incrementAndGet();
        submit(() -> {
            try {
                mesh(chunk, lod, withGrass && lod == 0);
            } finally {
                building.remove(key);
                inFlight.decrementAndGet();
            }
        });
    }

    /** Build a chunk's four meshes and hand them over in one call. */
    private void mesh(WatchChunk chunk, int lod, boolean withGrass) {
        Mesh ground = TerrainMesher.ground(chunk, lod);
        Mesh water = TerrainMesher.water(chunk, lod);
        Mesh flora = FloraMesher.flora(chunk, lod);
        Mesh grass = withGrass
                ? FloraMesher.grass(chunk, grassField, grassClock)
                : Mesh.empty(chunk.originX(), chunk.originY(), 0);
        chunk.setMeshes(lod, ground, water, flora, grass);
    }

    private void submit(Runnable task) {
        ExecutorService pool = pool();
        try {
            pool.execute(task);
        } catch (RuntimeException e) {
            // A rejected task is a chunk that stays missing for a frame, not a
            // crash: the next update will queue it again.
            inFlight.decrementAndGet();
        }
    }

    private synchronized ExecutorService pool() {
        if (workers == null) {
            AtomicInteger n = new AtomicInteger();
            ThreadFactory factory = r -> {
                Thread t = new Thread(r, "watch-chunk-" + n.incrementAndGet());
                t.setDaemon(true);
                // Below the frame thread: a chunk arriving late is a chunk
                // arriving late, and a frame arriving late is a stutter.
                t.setPriority(Thread.NORM_PRIORITY - 1);
                return t;
            };
            workers = Executors.newFixedThreadPool(workerCount, factory);
        }
        return workers;
    }

    /** Throw every chunk away, keeping the workers. */
    public void clear() {
        loaded.clear();
        building.clear();
    }

    @Override
    public synchronized void close() {
        if (workers != null) {
            workers.shutdownNow();
            workers = null;
        }
        loaded.clear();
        building.clear();
    }
}
