package com.larsons.engine.watch.world;

import com.larsons.engine.watch.render.FloraMesher;
import com.larsons.engine.watch.render.Mesh;
import com.larsons.engine.watch.render.TerrainMesher;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Which chunks exist, at what detail, and the workers that build them.
 *
 * <h2>Nothing is built on the frame that wants it</h2>
 *
 * <p>Generating a chunk is a thousand height samples, each of them eight noise
 * fields deep, plus the flora and the meshing — a few milliseconds, which is
 * most of a frame. Doing that while a frame waits is exactly the stutter a
 * streaming world exists to remove. So a frame says where the camera is, this
 * queues whatever is missing <b>nearest first</b> on a small pool of daemon
 * workers, and the frame draws what has arrived. What has not is a piece of
 * ground that appears a moment later at the edge of the view, which is what
 * every game of this shape does.
 *
 * <h2>Detail follows distance</h2>
 *
 * <p>A chunk's {@linkplain WatchChunk#lod() level of detail} is decided by how
 * far it is from the camera, and changing it is a re-mesh, not a re-generation
 * — the heightfield is the same data at every level. So walking toward a
 * hillside sharpens it for the price of the triangles, not the noise.
 *
 * <p>Grass is the exception that proves the rule: it exists only inside
 * {@link #grassRadius()} chunks, and those few meshes are rebuilt on a slow
 * cadence with the wind field advanced, which is how a meadow sways without
 * costing a single operation on a normal frame.
 *
 * <h2>…and detail follows a spyglass</h2>
 *
 * <p>A raised glass sets a {@link Focus}: an origin, a direction, a reach and a
 * magnification. Chunks inside that cone are <b>wanted even when they are far
 * outside the view radius</b>, and their level of detail is chosen from their
 * distance <em>divided by the magnification</em> — which is exactly what a
 * longer focal length does to a hillside. At ×8 a chunk twenty out is drawn as
 * though it were two and a half away, so it gets its bushes and its real
 * trunks, and the far shore in the eyepiece is the same ground the near one is
 * rather than a coarse impostor of it.
 *
 * <p>That is affordable for one reason: <b>the same narrowing that asks for the
 * detail pays for it.</b> A ×8 glass is a ten-degree frustum, so almost
 * everything in the ordinary ring fails {@code EyeCamera.boxVisible} and is
 * never submitted at all. The cone is a few hundred chunks of a circle whose
 * whole area would be thousands. The cost that is real is memory — those chunks
 * are held while the glass is up and retire to the LRU cache when it comes
 * down.
 *
 * <h2>Ground that has been built stays built</h2>
 *
 * <p>A chunk walked away from is <b>retained, not destroyed</b>. It moves out
 * of the active ring into a least-recently-used cache sized from the heap this
 * JVM was given ({@link com.larsons.engine.graphics.ChunkMemory}), and walking
 * back into it is a map lookup rather than a regeneration.
 *
 * <p>That is the single biggest thing this class does for how the game feels,
 * and it was previously not done at all: a chunk more than
 * {@link #EVICT_MARGIN} outside the view radius was dropped on the floor, so
 * walking to the lake and back rebuilt the entire path there — a few
 * milliseconds of noise per chunk, on the very workers that should have been
 * building the ground <em>ahead</em> of the player. Pacing back and forth over
 * a chunk boundary could regenerate the same ground indefinitely. On a machine
 * with sixteen gigabytes in it, throwing that work away to save forty megabytes
 * is the wrong trade by two orders of magnitude.
 *
 * <p>The cache is only ever an optimisation: a chunk is a pure function of
 * {@code (seed, x, y)}, so a cache miss is indistinguishable from a cache that
 * was never there. Which means the budget can be as small as a small heap
 * wants, and nothing else in the game has to know.
 *
 * <h2>Threads</h2>
 *
 * <p>{@code min(6, cores − 1)} of them, named {@code watch-chunk-N}, daemons so
 * a stuck build can never keep the game open. Each one builds a chunk to
 * completion and publishes it in one write to a concurrent map; nothing mutates
 * a published chunk except a re-mesh, which builds new meshes off to the side
 * and swaps them in with a single call.
 */
public final class ChunkStreamer implements AutoCloseable {

    /** How many chunks out the world is generated by default. */
    public static final int DEFAULT_VIEW_RADIUS = 10;

    /** How many chunks out the finest detail — and the grass — reaches. */
    public static final int DEFAULT_DETAIL_RADIUS = 2;

    /** How far past the view radius a chunk is kept before being thrown away. */
    private static final int EVICT_MARGIN = 3;

    /**
     * The furthest a focus cone may reach, in chunks — a kilometre and a bit.
     *
     * <p>A ceiling rather than a policy: the scene picks the reach from the
     * glass's power and from whether there is a card behind the frame, and this
     * is only here so that no caller can ask for a hundred thousand chunks.
     */
    public static final int MAX_FOCUS_RADIUS = 34;

    /** How long between rebuilds of the near grass, in seconds. */
    private static final double GRASS_PERIOD = 2.2;

    private final TerrainField field;
    private final Flora flora;
    private final GrassField grassField;

    private final Map<Long, WatchChunk> loaded = new ConcurrentHashMap<>();
    private final Map<Long, Boolean> building = new ConcurrentHashMap<>();
    private final AtomicLong revisions = new AtomicLong(1);
    private final AtomicInteger inFlight = new AtomicInteger();

    /**
     * Chunks that have been built and walked away from, newest use last.
     *
     * <p>A {@link LinkedHashMap} in access order <em>is</em> the LRU, and its
     * {@code removeEldestEntry} hook is the eviction. Synchronised on itself
     * rather than concurrent: it is touched once per chunk that crosses the
     * ring's edge — a handful per second at a walking pace — and access-ordered
     * maps mutate on read, so a concurrent one would be neither.
     */
    private final Map<Long, WatchChunk> retained;

    /** How many chunks the cache may hold, from the heap this JVM was given. */
    private final int cacheBudget;

    /** How many times a chunk was taken back out of the cache instead of built. */
    private long recalled;

    private ExecutorService workers;
    private final int workerCount;
    private final int maxInFlight;

    private int viewRadius = DEFAULT_VIEW_RADIUS;
    private int detailRadius = DEFAULT_DETAIL_RADIUS;
    private int grassRadius = 1;
    private double grassClock;
    private double grassRebuiltAt = -GRASS_PERIOD;
    private long generated;

    /**
     * Where a glass is pointed, or {@code null} for the naked eye.
     *
     * <p>Volatile because the frame thread writes it and the same thread reads
     * it on the next {@link #update} — but also because a worker's
     * {@code lodFor} could otherwise see a stale one, and a chunk built at the
     * wrong detail is a chunk re-meshed a frame later for nothing.
     */
    private volatile Focus focus;

    public ChunkStreamer(long seed) {
        this(new TerrainField(seed));
    }

    public ChunkStreamer(TerrainField field) {
        this(field, com.larsons.engine.graphics.ChunkMemory.chunkCacheBudget());
    }

    /**
     * A streamer with a stated cache size — for tests, which need to be able to
     * ask what happens when the cache is full without allocating a heap.
     */
    public ChunkStreamer(TerrainField field, int cacheBudget) {
        this.field = field;
        this.flora = new Flora(field.seed(), field);
        this.grassField = new GrassField(field.seed());
        this.workerCount = Math.max(1, Math.min(6, Runtime.getRuntime().availableProcessors() - 1));
        this.maxInFlight = workerCount * 3;
        this.cacheBudget = Math.max(0, cacheBudget);
        this.retained = new java.util.LinkedHashMap<>(64, 0.75f, true) {
            @Override
            protected boolean removeEldestEntry(Map.Entry<Long, WatchChunk> eldest) {
                return size() > ChunkStreamer.this.cacheBudget;
            }
        };
    }

    /** The generator underneath — what the physics asks for ground it cannot see. */
    public TerrainField field() { return field; }

    /** The grass field, so the renderer can ask how long a blade is at a point. */
    public GrassField grassField() { return grassField; }

    /** How many chunks out the world is generated. */
    public int viewRadius() { return viewRadius; }

    /**
     * Set how far the world is generated, in chunks. A backend with a depth
     * buffer can afford far more than one painting back to front, so the scene
     * sets this from what it found rather than from a constant.
     */
    public void setViewRadius(int chunks) {
        this.viewRadius = Math.max(1, Math.min(48, chunks));
    }

    public int detailRadius() { return detailRadius; }

    public void setDetailRadius(int chunks) {
        this.detailRadius = Math.max(0, Math.min(viewRadius, chunks));
    }

    /**
     * Where a spyglass is pointed, and how much world it is asking for.
     *
     * <p>Everything here is in world units except {@link #radius()}, which is
     * in chunks because it is a ring size like {@link #viewRadius()} and is
     * clamped against {@link #MAX_FOCUS_RADIUS}.
     *
     * @param x             where the eye is
     * @param dirX          the way it is looking, flattened onto the ground and
     *                      normalised — the pitch is deliberately dropped,
     *                      because a chunk is a column and looking up the side
     *                      of a mountain still wants the mountain
     * @param radius        how far down that line to build, in chunks
     * @param cosHalfAngle  the cosine of the cone's half angle; a chunk whose
     *                      bearing is outside it is not wanted
     * @param magnification what to divide a chunk's distance by when choosing
     *                      its level of detail — the whole of "renders distant
     *                      areas in full detail", in one number
     */
    public record Focus(double x, double y, double dirX, double dirY, int radius,
                        double cosHalfAngle, double magnification) {

        /**
         * A cone from an eye down a heading.
         *
         * @param yaw       the heading, radians clockwise from north, as
         *                  {@code EyeCamera} means it
         * @param halfAngle how wide the cone is either side of that, radians
         */
        public static Focus looking(double x, double y, double yaw, int radius,
                                    double halfAngle, double magnification) {
            return new Focus(x, y, Math.sin(yaw), -Math.cos(yaw),
                    Math.max(1, Math.min(MAX_FOCUS_RADIUS, radius)),
                    Math.cos(Math.max(0.02, Math.min(Math.PI / 2, halfAngle))),
                    Math.max(1, magnification));
        }

        /** Whether a chunk's middle is inside the cone. */
        public boolean holds(int cx, int cy) {
            double wx = cx * (double) WatchChunk.SIZE + WatchChunk.SIZE / 2.0 - x;
            double wy = cy * (double) WatchChunk.SIZE + WatchChunk.SIZE / 2.0 - y;
            double distance = Math.hypot(wx, wy);
            if (distance > radius * (double) WatchChunk.SIZE) return false;
            // The chunks around the eye are always in: at any real half-angle
            // the cone is narrower than a chunk for the first few, and a hole
            // under the player's feet is not what a spyglass is for.
            if (distance <= WatchChunk.SIZE * 1.5) return true;
            return (wx * dirX + wy * dirY) / distance >= cosHalfAngle;
        }
    }

    /**
     * Point the detail down a line, or pass {@code null} to stop.
     *
     * <p>Called every frame while a glass is up — it is one field write, and
     * the cone is walked from it on the same {@link #update} the ordinary ring
     * is.
     */
    public void setFocus(Focus focus) {
        this.focus = focus == null || focus.radius() <= 0 ? null : focus;
    }

    /** Where the glass is pointed, or {@code null}. */
    public Focus focus() { return focus; }

    /** How many chunks out individual blades of grass are built. */
    public int grassRadius() { return grassRadius; }

    public void setGrassRadius(int chunks) {
        this.grassRadius = Math.max(0, Math.min(6, chunks));
    }

    /** How many chunks have been generated since this streamer started. */
    public long generatedCount() { return generated; }

    /** How many chunks are in memory. */
    public int loadedCount() { return loaded.size(); }

    /** How many builds are queued or running. */
    public int pending() { return inFlight.get(); }

    /** Every chunk currently in memory. */
    public Collection<WatchChunk> chunks() { return loaded.values(); }

    /** The chunk at a chunk coordinate, or {@code null} if it is not built yet. */
    public WatchChunk chunk(int cx, int cy) { return loaded.get(WatchChunk.key(cx, cy)); }

    /** The chunk containing a world position, or {@code null}. */
    public WatchChunk chunkAt(double x, double y) {
        return chunk(WatchChunk.chunkOf(x), WatchChunk.chunkOf(y));
    }

    /**
     * The ground's height at a world position.
     *
     * <p>From the chunk when there is one — a bilinear read of four samples,
     * which is what the triangles the player can see were built from, so they
     * stand on the ground rather than a few centimetres above or below it. When
     * there is not, straight from the generator: slower, exact, and never
     * absent, which is what a player who has just been teleported needs.
     */
    public double groundAt(double x, double y) {
        WatchChunk chunk = chunkAt(x, y);
        return chunk != null ? chunk.groundAt(x, y) : field.heightAt(x, y);
    }

    /** The biome at a world position, from the chunk when there is one. */
    public WatchBiome biomeAt(double x, double y) {
        WatchChunk chunk = chunkAt(x, y);
        return chunk != null ? chunk.biomeAtWorld(x, y) : field.biomeAt(x, y);
    }

    /** Whether a world position is under water. */
    public boolean underwater(double x, double y) {
        return groundAt(x, y) < TerrainField.WATER_LEVEL;
    }

    /**
     * Keep the world around a point loaded.
     *
     * <p>Called once a frame with the camera's position. Queues what is
     * missing, re-meshes what has changed detail, and drops what has been
     * walked away from — all of it bounded, so no single call can cost a frame.
     *
     * @param dt seconds since the last call, for the grass's own clock
     */
    public void update(double centreX, double centreY, double dt) {
        grassClock += dt;
        int ccx = WatchChunk.chunkOf(centreX);
        int ccy = WatchChunk.chunkOf(centreY);

        evictBeyond(ccx, ccy);

        boolean grassDue = grassClock - grassRebuiltAt >= GRASS_PERIOD;
        if (grassDue) grassRebuiltAt = grassClock;

        // Nearest first: the chunk under the player's feet matters more than
        // the one at the horizon, and a queue that does not say so fills the
        // view from the outside in.
        List<int[]> wanted = ring(ccx, ccy, viewRadius);
        for (int[] at : wanted) {
            if (inFlight.get() >= maxInFlight) break;
            want(at[0], at[1], ccx, ccy, grassDue);
        }

        // Then whatever the glass is looking at, which is outside that ring by
        // construction — nearest first again, so the eyepiece fills from the
        // middle distance outward rather than from the horizon in.
        Focus glass = focus;
        if (glass == null) return;
        for (int[] at : cone(glass)) {
            if (inFlight.get() >= maxInFlight) break;
            want(at[0], at[1], ccx, ccy, grassDue);
        }
    }

    /** Build, re-mesh or leave alone one chunk the camera wants. */
    private void want(int cx, int cy, int ccx, int ccy, boolean grassDue) {
        long key = WatchChunk.key(cx, cy);
        WatchChunk chunk = loaded.get(key);
        int lod = lodFor(cx, cy, ccx, ccy);
        if (chunk == null) {
            queueBuild(cx, cy, lod);
        } else if (chunk.lod() != lod) {
            queueMesh(chunk, lod, grassDue);
        } else if (grassDue && lod == 0 && withinGrass(cx - ccx, cy - ccy)) {
            queueMesh(chunk, lod, true);
        }
    }

    /**
     * Build everything within a radius and wait for it — for tests, for a
     * screenshot, and for the moment a save is loaded and the player should not
     * see the world assemble itself around them.
     */
    public void loadNow(double centreX, double centreY, int radius) {
        int ccx = WatchChunk.chunkOf(centreX);
        int ccy = WatchChunk.chunkOf(centreY);
        for (int[] at : ring(ccx, ccy, radius)) {
            long key = WatchChunk.key(at[0], at[1]);
            if (loaded.containsKey(key)) continue;
            int lod = lodFor(at[0], at[1], ccx, ccy);
            WatchChunk kept = recall(key);
            if (kept != null) {
                loaded.put(key, kept);
                recalled++;
                if (kept.lod() != lod) {
                    mesh(kept, lod, lod == 0 && withinGrass(at[0] - ccx, at[1] - ccy));
                }
                continue;
            }
            WatchChunk chunk = WatchChunk.generate(field, flora, at[0], at[1],
                    revisions.getAndIncrement());
            // The same grass gate the streaming path uses. Passing `true` here
            // put individual blades on every chunk in the ring rather than on
            // the near few, which is most of a frame's triangles and made any
            // measurement taken through this method wrong about the game.
            mesh(chunk, lod, lod == 0 && withinGrass(at[0] - ccx, at[1] - ccy));
            loaded.put(key, chunk);
            generated++;
        }
    }

    private boolean withinGrass(int dx, int dy) {
        return Math.max(Math.abs(dx), Math.abs(dy)) <= grassRadius;
    }

    /**
     * The detail a chunk is drawn at.
     *
     * <p>Its distance from the camera in chunks — <b>divided by the
     * magnification when it is inside a focus cone</b>, which is the one line
     * that makes a spyglass render distant ground finely rather than merely
     * bigger. A chunk in the cone is never drawn more coarsely than its plain
     * distance would give it, so raising a glass can only ever sharpen the
     * view.
     */
    private int lodFor(int cx, int cy, int ccx, int ccy) {
        int distance = Math.max(Math.abs(cx - ccx), Math.abs(cy - ccy));
        Focus glass = focus;
        if (glass != null && glass.holds(cx, cy)) {
            distance = (int) Math.floor(distance / glass.magnification());
        }
        return lodAt(distance);
    }

    /** The detail a chunk this many chunks out is drawn at. */
    private int lodAt(int distance) {
        if (distance <= detailRadius) return 0;
        if (distance <= detailRadius * 2 + 1) return 1;
        if (distance <= detailRadius * 4 + 3) return 2;
        return WatchChunk.MAX_LOD;
    }

    /**
     * The chunks inside a focus cone, nearest first.
     *
     * <p>The bounding square of the cone, filtered. That is up to a few
     * thousand cheap tests once a frame, against a cone whose contents are a
     * few hundred — worth it rather than trying to walk the wedge exactly,
     * which is fiddly and no faster at this size.
     */
    private static List<int[]> cone(Focus focus) {
        int ccx = WatchChunk.chunkOf(focus.x());
        int ccy = WatchChunk.chunkOf(focus.y());
        int radius = focus.radius();
        List<int[]> out = new ArrayList<>();
        for (int dy = -radius; dy <= radius; dy++) {
            for (int dx = -radius; dx <= radius; dx++) {
                int cx = ccx + dx, cy = ccy + dy;
                if (focus.holds(cx, cy)) out.add(new int[]{cx, cy});
            }
        }
        out.sort(Comparator.comparingInt(at -> {
            int dx = at[0] - ccx, dy = at[1] - ccy;
            return dx * dx + dy * dy;
        }));
        return out;
    }

    /** Chunk coordinates within a radius of a centre, nearest first. */
    private static List<int[]> ring(int ccx, int ccy, int radius) {
        List<int[]> out = new ArrayList<>((radius * 2 + 1) * (radius * 2 + 1));
        for (int dy = -radius; dy <= radius; dy++) {
            for (int dx = -radius; dx <= radius; dx++) {
                out.add(new int[]{ccx + dx, ccy + dy});
            }
        }
        out.sort(Comparator.comparingInt(at -> {
            int dx = at[0] - ccx, dy = at[1] - ccy;
            return dx * dx + dy * dy;
        }));
        return out;
    }

    /**
     * Move everything outside the ring into the cache.
     *
     * <p>Retired rather than destroyed — see the class note. A chunk here keeps
     * its meshes and its revision, so recalling it draws with the buffers a
     * backend already has rather than forcing a fresh upload.
     */
    private void evictBeyond(int ccx, int ccy) {
        int limit = viewRadius + EVICT_MARGIN;
        Focus glass = focus;
        for (Map.Entry<Long, WatchChunk> entry : loaded.entrySet()) {
            long key = entry.getKey();
            int cx = (int) (key >> 32);
            int cy = (int) (key & 0xFFFFFFFFL);
            if (Math.max(Math.abs(cx - ccx), Math.abs(cy - ccy)) <= limit) continue;
            // A chunk the glass is looking at is in view however far away it
            // is; evicting it would be evicting the thing on screen.
            if (glass != null && glass.holds(cx, cy)) continue;
            WatchChunk gone = loaded.remove(key);
            if (gone != null) retire(key, gone);
        }
    }

    private void retire(long key, WatchChunk chunk) {
        if (cacheBudget == 0) return;
        synchronized (retained) {
            retained.put(key, chunk);
        }
    }

    /** Take a chunk back out of the cache, or {@code null} if it is not there. */
    private WatchChunk recall(long key) {
        if (cacheBudget == 0) return null;
        synchronized (retained) {
            return retained.remove(key);
        }
    }

    /** How many chunks are being kept against a return visit. */
    public int cachedCount() {
        synchronized (retained) {
            return retained.size();
        }
    }

    /** The ceiling on that, from the heap this JVM was given. */
    public int cacheBudget() { return cacheBudget; }

    /** How many chunks have been recalled rather than regenerated. */
    public long recalledCount() { return recalled; }

    private void queueBuild(int cx, int cy, int lod) {
        long key = WatchChunk.key(cx, cy);
        if (building.putIfAbsent(key, Boolean.TRUE) != null) return;

        // Built before, and kept. Ground that has already been generated is
        // ground that never has to be generated again, and putting it straight
        // back is the whole point of holding on to it: no worker, no noise, no
        // frame of missing hillside where the player has just turned round.
        WatchChunk kept = recall(key);
        if (kept != null) {
            loaded.put(key, kept);
            recalled++;
            building.remove(key);
            // Its detail may not be what this distance wants any more; that is
            // a re-mesh of data it already has, queued the usual way below.
            if (kept.lod() != lod) queueMesh(kept, lod, false);
            return;
        }

        inFlight.incrementAndGet();
        submit(() -> {
            try {
                WatchChunk chunk = WatchChunk.generate(field, flora, cx, cy,
                        revisions.getAndIncrement());
                mesh(chunk, lod, lod == 0);
                loaded.put(key, chunk);
                generated++;
            } finally {
                building.remove(key);
                inFlight.decrementAndGet();
            }
        });
    }

    private void queueMesh(WatchChunk chunk, int lod, boolean withGrass) {
        long key = chunk.key();
        if (building.putIfAbsent(key, Boolean.TRUE) != null) return;
        inFlight.incrementAndGet();
        submit(() -> {
            try {
                mesh(chunk, lod, withGrass && lod == 0);
            } finally {
                building.remove(key);
                inFlight.decrementAndGet();
            }
        });
    }

    /** Build a chunk's four meshes and hand them over in one call. */
    private void mesh(WatchChunk chunk, int lod, boolean withGrass) {
        // Claim the revision first: all four meshes carry it, and it is what
        // tells a backend that has already uploaded this chunk that what it
        // holds is now the wrong level of detail. See WatchChunk.beginMesh.
        chunk.beginMesh();
        Mesh ground = TerrainMesher.ground(chunk, lod);
        Mesh water = TerrainMesher.water(chunk, lod);
        Mesh flora = FloraMesher.flora(chunk, lod);
        Mesh grass = withGrass
                ? FloraMesher.grass(chunk, grassField, grassClock)
                : Mesh.empty(chunk.originX(), chunk.originY(), 0);
        chunk.setMeshes(lod, ground, water, flora, grass);
    }

    private void submit(Runnable task) {
        ExecutorService pool = pool();
        try {
            pool.execute(task);
        } catch (RuntimeException e) {
            // A rejected task is a chunk that stays missing for a frame, not a
            // crash: the next update will queue it again.
            inFlight.decrementAndGet();
        }
    }

    private synchronized ExecutorService pool() {
        if (workers == null) {
            AtomicInteger n = new AtomicInteger();
            ThreadFactory factory = r -> {
                Thread t = new Thread(r, "watch-chunk-" + n.incrementAndGet());
                t.setDaemon(true);
                // Below the frame thread: a chunk arriving late is a chunk
                // arriving late, and a frame arriving late is a stutter.
                t.setPriority(Thread.NORM_PRIORITY - 1);
                return t;
            };
            workers = Executors.newFixedThreadPool(workerCount, factory);
        }
        return workers;
    }

    /** Throw every chunk away — the cache included — keeping the workers. */
    public void clear() {
        loaded.clear();
        building.clear();
        synchronized (retained) {
            retained.clear();
        }
    }

    @Override
    public synchronized void close() {
        if (workers != null) {
            workers.shutdownNow();
            workers = null;
        }
        clear();
    }
}
