package com.larsons.engine.watch;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * One map: a square of country, drawn the moment somebody made it, and whatever
 * has been written on it since.
 *
 * <h2>The picture is not in here</h2>
 *
 * <p><b>A chart stores where it is, not what it looks like.</b> The ground in
 * this world is a pure function of {@code (seed, x, y)} — see
 * {@link com.larsons.engine.watch.world.TerrainField} — so the picture of a
 * square of it is a pure function of the same three numbers and can be
 * regenerated by anybody who knows the seed. That is exactly the argument
 * {@link Shops} makes for not sending a trading post over the wire, and it
 * lands in the same place: a map is four numbers and a name on the wire and in
 * the save, and {@code watch.render.ChartImage} paints it from the seed on
 * whichever machine is looking at it.
 *
 * <p>What genuinely cannot be derived is what a <em>person</em> did: the
 * landmarks that were standing when the map was made, the pen, and the name.
 * Those are the whole of this class's state, and they are what travels.
 *
 * <h2>Why the landmarks are frozen</h2>
 *
 * <p>The icons are collected once, by {@link Survey}, at the moment the map is
 * drawn, and are never touched again. That is the difference between a map and
 * a minimap: a map is a record of what was there when somebody surveyed it, so
 * a camp you build next week is not on last week's map and the feeder that has
 * since rotted away still is. It is also why a map is worth re-drawing, which is
 * the only reason to ever make a second one of the same place.
 *
 * <h2>Ink is in metres</h2>
 *
 * <p>Every stroke and every note is stored in <b>world coordinates</b> rather
 * than as a fraction of the map's own frame. It costs nothing — the panel
 * converts once either way — and it buys the one thing that makes a
 * {@linkplain Cartography.Board map board} work: two maps of neighbouring
 * country, pinned side by side, carry ink that is already in the same space, so
 * a line drawn across the edge of one meets the line drawn across the edge of
 * the other. Ink stored per-map in map coordinates would have to be transformed
 * by whichever map it came from every time anything drew it, and the first
 * thing to get that wrong would be the board.
 */
public final class Chart {

    /** The smallest map anybody can draw, as a half-span in metres. */
    public static final double MIN_RADIUS = 64;

    /**
     * …and the largest.
     *
     * <p>A limit rather than a design: the half-span is
     * {@linkplain #radius() whatever the machine that drew it could see}, and a
     * card with a long ring and a detail setting wound up is the honest upper
     * end of that. This is the guard on the number arriving over the wire, so a
     * client cannot ask the host for a map of the whole plane and a picture
     * nothing can paint.
     */
    public static final double MAX_RADIUS = 4096;

    /** How many points one pen stroke may carry. */
    public static final int MAX_STROKE_POINTS = 240;

    /** How long a written note may be. */
    public static final int MAX_NOTE_LENGTH = 40;

    /** How long a map's name may be. */
    public static final int MAX_NAME_LENGTH = 28;

    /** What a map is called before anybody renames it. */
    public static final String UNTITLED = "Untitled Map";

    /**
     * The sizes a map may be, as half-spans in metres, each twice the last.
     *
     * <p><b>A ladder rather than whatever number the machine happened to
     * report</b>, and the reason is the board. Two maps combine into a larger
     * one by being laid out in world coordinates and drawn where they belong —
     * which works for any two maps, but only <em>looks</em> like one map when
     * their edges meet. Edges meet when the spans are the same or one is a
     * whole multiple of the other, and when the centres sit on a common grid.
     * Doubling sizes give the first; {@link #snap} gives the second.
     *
     * <p>So a card and a laptop, whose render distances have nothing to do with
     * each other, still produce maps that tile: the laptop's is a quarter of the
     * card's and drops into it exactly, the way a page of a road atlas drops
     * into the index map at the front.
     */
    public static final double[] RADII = {64, 128, 256, 512, 1024, 2048, 4096};

    /**
     * The map size for a machine that can see {@code reach} metres.
     *
     * <p><b>Twice the reach, rounded up the ladder</b> — which is the arithmetic
     * that makes "the map spans the whole render distance" true wherever you are
     * standing in it rather than only in the middle. {@link #snap} moves the
     * centre by at most half a radius, so the nearest edge is never closer than
     * {@code radius − radius/2 = radius/2}; with {@code radius ≥ 2 × reach} that
     * half-radius is itself at least the reach, and everything the machine
     * currently has loaded is inside the square, in every direction, from
     * wherever the player happened to press the key.
     *
     * <p>The map is therefore comfortably larger than the ring it was drawn
     * from, which is the right way round: a map you have walked off the edge of
     * is not a map.
     */
    public static double radiusFor(double reach) {
        double want = Math.max(reach, 0) * 2;
        for (double radius : RADII) {
            if (radius >= want) return radius;
        }
        return MAX_RADIUS;
    }

    /**
     * A centre put on the grid its own size defines.
     *
     * <p>Half-span steps, not whole ones: a whole-span grid gives tiles that
     * abut and nothing in between, so two maps drawn a few hundred metres apart
     * land on the same tile and the second one is a duplicate of the first.
     * Stepping by the radius lets a walk lay down a row of maps that each
     * overlap their neighbour by half — and because the picture is a function
     * of the ground rather than of the map, an overlap is invisible: the two
     * halves agree pixel for pixel.
     */
    public static double snap(double v, double radius) {
        return Math.round(v / radius) * radius;
    }

    /**
     * The pen's colours.
     *
     * <p>Six, and they are the six a person actually has in a satchel: a stick
     * of charcoal and five earths. The number is the point — a colour picker is
     * a thing to fiddle with, and six swatches along the bottom of the panel is
     * a thing you press once and then draw.
     */
    public enum Ink {
        CHARCOAL("Charcoal", 0x241F1B),
        RED("Red Ochre", 0xB4402F),
        BLUE("Woad", 0x2F5F9E),
        GREEN("Verdigris", 0x2E7A55),
        AMBER("Amber", 0xC98A22),
        VIOLET("Violet", 0x7A4A9E);

        private final String label;
        private final int rgb;

        Ink(String label, int rgb) {
            this.label = label;
            this.rgb = rgb;
        }

        /** What the swatch is called. */
        public String label() { return label; }

        /** {@code 0xRRGGBB}. */
        public int rgb() { return rgb; }

        /** The ink an index means, tolerating anything out of range. */
        public static Ink at(int index) {
            Ink[] all = values();
            return all[Math.floorMod(index, all.length)];
        }
    }

    /**
     * What kind of thing an icon on the map stands for.
     *
     * <p>Seven, and every one of them is something the world already has: there
     * is no icon here for a feature invented so that the map would have
     * something to draw. {@link Survey} is the other half of the sentence — it
     * is where each of these is found — and adding a kind means adding a pass
     * there and a shape in the panel, in that order.
     */
    public enum Kind {
        /** A trading post. See {@link Shops}. */
        SHOP("Trading post", 0xC9A227),
        /**
         * Somewhere the party lives. See
         * {@link com.larsons.engine.watch.home.Homestead}.
         */
        CAMP("Camp", 0xB4763A),
        /** A feeder standing out. See {@link Lure}. */
        FEEDER("Feeder", 0x8FA84C),
        /** A tree somebody planted. See {@link com.larsons.engine.watch.world.Grove}. */
        PLANTING("Planting", 0x3F8A46),
        /** A boat, drawn up on a shore. See {@link Boats}. */
        BOAT("Boat", 0xA9D6E0),
        /** Where a species was first recorded. See {@link Sighting}. */
        SIGHTING("First sighting", 0xD8557A),
        /** A local high point, read off the ground itself. */
        SUMMIT("High ground", 0x9A9086);

        private final String label;
        private final int rgb;

        Kind(String label, int rgb) {
            this.label = label;
            this.rgb = rgb;
        }

        /** What the key down the side of the map calls it. */
        public String label() { return label; }

        /** The colour the icon is drawn in. */
        public int rgb() { return rgb; }

        /** The kind a saved name means, or {@code null}. */
        public static Kind of(String key) {
            if (key == null) return null;
            for (Kind k : values()) {
                if (k.name().equalsIgnoreCase(key)) return k;
            }
            return null;
        }
    }

    /** One icon: what it is, where it is, and what it is called. */
    public record Landmark(Kind kind, double x, double y, String label) {

        Map<String, Object> toMap() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("k", kind.name().toLowerCase());
            m.put("x", x);
            m.put("y", y);
            if (label != null && !label.isBlank()) m.put("l", label);
            return m;
        }

        static Landmark fromMap(Map<String, Object> m) {
            Kind kind = Kind.of(WatchJson.str(m, "k", null));
            if (kind == null) return null;
            return new Landmark(kind, WatchJson.num(m, "x", 0), WatchJson.num(m, "y", 0),
                    WatchJson.str(m, "l", kind.label()));
        }
    }

    /**
     * One pen stroke, in world metres.
     *
     * <p>{@code xs} and {@code ys} are parallel and the same length, which is
     * checked once here rather than at each of the four places that walk them.
     * They are copied in, so a stroke is immutable and can be handed to a
     * drawing thread without a thought.
     */
    public record Stroke(long id, Ink ink, String by, double[] xs, double[] ys) {

        public Stroke {
            if (xs == null || ys == null) {
                xs = new double[0];
                ys = new double[0];
            }
            int n = Math.min(Math.min(xs.length, ys.length), MAX_STROKE_POINTS);
            xs = java.util.Arrays.copyOf(xs, n);
            ys = java.util.Arrays.copyOf(ys, n);
        }

        /** How many points it has. */
        public int size() { return xs.length; }

        /** Whether there is anything to draw. */
        public boolean drawable() { return xs.length >= 2; }

        /**
         * How far a point is from the nearest point of this stroke, in metres —
         * what the eraser picks by.
         *
         * <p>Vertex distance rather than distance to the segments between them.
         * A stroke laid down by a hand moving over a panel has points every few
         * pixels, so the two answers differ by less than the eraser's own
         * radius, and the cheap one cannot be got wrong.
         */
        public double distanceTo(double x, double y) {
            double best = Double.MAX_VALUE;
            for (int i = 0; i < xs.length; i++) {
                best = Math.min(best, Math.hypot(xs[i] - x, ys[i] - y));
            }
            return best;
        }

        Map<String, Object> toMap() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            m.put("i", ink.ordinal());
            if (by != null) m.put("by", by);
            // One flat array rather than a list of pairs: a stroke is the only
            // thing about a map that is more than a handful of numbers, and
            // {"x":..,"y":..} per point triples what a scribble costs on the
            // wire for nothing anybody reads.
            List<Object> flat = new ArrayList<>(xs.length * 2);
            for (int i = 0; i < xs.length; i++) {
                flat.add(round(xs[i]));
                flat.add(round(ys[i]));
            }
            m.put("p", flat);
            return m;
        }

        static Stroke fromMap(Map<String, Object> m) {
            List<Object> flat = WatchJson.list(m, "p");
            int n = flat.size() / 2;
            double[] xs = new double[n];
            double[] ys = new double[n];
            for (int i = 0; i < n; i++) {
                xs[i] = flat.get(i * 2) instanceof Number a ? a.doubleValue() : 0;
                ys[i] = flat.get(i * 2 + 1) instanceof Number b ? b.doubleValue() : 0;
            }
            return new Stroke(WatchJson.big(m, "id", 0),
                    Ink.at(WatchJson.integer(m, "i", 0)), WatchJson.str(m, "by", null),
                    xs, ys);
        }
    }

    /**
     * A few words written at a point.
     *
     * <p>The other half of a pen, and the half that carries the information. A
     * scribble round a clearing says "here"; "otters, dusk" says why.
     */
    public record Note(long id, Ink ink, String by, double x, double y, String text) {

        Map<String, Object> toMap() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            m.put("i", ink.ordinal());
            if (by != null) m.put("by", by);
            m.put("x", round(x));
            m.put("y", round(y));
            m.put("s", text);
            return m;
        }

        static Note fromMap(Map<String, Object> m) {
            String text = WatchJson.str(m, "s", "");
            if (text.isBlank()) return null;
            return new Note(WatchJson.big(m, "id", 0),
                    Ink.at(WatchJson.integer(m, "i", 0)), WatchJson.str(m, "by", null),
                    WatchJson.num(m, "x", 0), WatchJson.num(m, "y", 0),
                    trim(text, MAX_NOTE_LENGTH));
        }
    }

    private final long id;
    private final double centreX, centreY, radius;
    private final String maker;
    private final long madeAt;
    private final List<Landmark> landmarks;

    private String name;

    /**
     * The board this map is pinned to, or {@code 0} while it is in a satchel.
     *
     * <p>On the map rather than on the board, so a map is in exactly one place:
     * a list of pinned ids on the board and an owner on the map would be two
     * records of the same fact, and the first bug either of them ever has is
     * disagreeing.
     */
    private long boardId;

    /** Whose satchel it is in while {@link #boardId} is {@code 0}. */
    private int owner;

    private final List<Stroke> strokes = new ArrayList<>();
    private final List<Note> notes = new ArrayList<>();

    public Chart(long id, String name, double centreX, double centreY, double radius,
                 String maker, long madeAt, List<Landmark> landmarks) {
        this.id = id;
        this.name = trim(name == null || name.isBlank() ? UNTITLED : name, MAX_NAME_LENGTH);
        this.centreX = centreX;
        this.centreY = centreY;
        this.radius = Math.max(MIN_RADIUS, Math.min(MAX_RADIUS, radius));
        this.maker = maker;
        this.madeAt = madeAt;
        this.landmarks = landmarks == null ? List.of() : List.copyOf(landmarks);
    }

    public long id() { return id; }

    /** What it is called; changed at will from the satchel. */
    public String name() { return name; }

    /** Rename it. Blank is refused — a map with no name cannot be picked out of a list. */
    public void setName(String to) {
        if (to == null || to.isBlank()) return;
        this.name = trim(to, MAX_NAME_LENGTH);
    }

    public double centreX() { return centreX; }

    public double centreY() { return centreY; }

    /**
     * Half the width of the country it covers, in metres.
     *
     * <p>Taken from the render distance of the machine that drew it, so the map
     * covers exactly as far as its maker could see when they made it. That is
     * what makes a map feel like a record of a place rather than a fixed-size
     * item: a walk on a card covers half a kilometre a side, and the same walk
     * on a laptop drawing through Java2D covers the smaller circle that laptop
     * was actually showing.
     */
    public double radius() { return radius; }

    /** How wide it is, in metres. */
    public double span() { return radius * 2; }

    public double minX() { return centreX - radius; }

    public double maxX() { return centreX + radius; }

    public double minY() { return centreY - radius; }

    public double maxY() { return centreY + radius; }

    /** Who drew it. */
    public String maker() { return maker; }

    /** When, in wall-clock millis. */
    public long madeAt() { return madeAt; }

    /** Whether a world point is on this map at all. */
    public boolean covers(double x, double y) {
        return x >= minX() && x <= maxX() && y >= minY() && y <= maxY();
    }

    /** The icons that were collected when it was drawn. */
    public List<Landmark> landmarks() { return landmarks; }

    /** Every icon of one kind. */
    public List<Landmark> landmarks(Kind kind) {
        List<Landmark> out = new ArrayList<>();
        for (Landmark landmark : landmarks) {
            if (landmark.kind() == kind) out.add(landmark);
        }
        return out;
    }

    /** The pen strokes on it, in the order they were drawn. */
    public List<Stroke> strokes() { return List.copyOf(strokes); }

    /** The notes written on it. */
    public List<Note> notes() { return List.copyOf(notes); }

    /** How many marks of either sort it carries. */
    public int marks() { return strokes.size() + notes.size(); }

    /** Which board it is pinned to, or {@code 0}. */
    public long boardId() { return boardId; }

    /** Whether it is on a board rather than in somebody's satchel. */
    public boolean pinned() { return boardId != 0; }

    /** Pin it to a board, or pass {@code 0} to take it back. */
    public void setBoardId(long boardId) { this.boardId = Math.max(0, boardId); }

    /** Whose satchel it is in. */
    public int owner() { return owner; }

    public void setOwner(int owner) { this.owner = owner; }

    /** Add a stroke. Anything with fewer than two points is not a line. */
    public void add(Stroke stroke) {
        if (stroke != null && stroke.drawable()) strokes.add(stroke);
    }

    /** Add a note. */
    public void add(Note note) {
        if (note != null && !note.text().isBlank()) notes.add(note);
    }

    /**
     * Rub out one mark by id, stroke or note.
     *
     * <p>One method for both because the eraser is one tool: the panel picks
     * whichever mark is nearest the pointer and asks for it by id, and which of
     * the two lists it happened to be in is not a thing the player chose.
     *
     * @return whether anything was rubbed out
     */
    public boolean erase(long markId) {
        return strokes.removeIf(s -> s.id() == markId)
                | notes.removeIf(n -> n.id() == markId);
    }

    /** The mark nearest a point within {@code within} metres, or {@code 0}. */
    public long markNear(double x, double y, double within) {
        long best = 0;
        double bestDistance = within;
        for (Stroke stroke : strokes) {
            double d = stroke.distanceTo(x, y);
            if (d < bestDistance) {
                bestDistance = d;
                best = stroke.id();
            }
        }
        for (Note note : notes) {
            double d = Math.hypot(note.x() - x, note.y() - y);
            if (d < bestDistance) {
                bestDistance = d;
                best = note.id();
            }
        }
        return best;
    }

    /** The scale bar's figure: how many metres a map this size is across. */
    public String describe() {
        long across = Math.round(span());
        String size = across >= 1000
                ? String.format("%.1f km", across / 1000.0)
                : across + " m";
        return size + " across  ·  drawn by " + (maker == null ? "somebody" : maker);
    }

    // --- persistence ----------------------------------------------------------------

    public Map<String, Object> toMap() {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("id", id);
        m.put("n", name);
        m.put("x", round(centreX));
        m.put("y", round(centreY));
        m.put("r", round(radius));
        if (maker != null) m.put("by", maker);
        m.put("t", madeAt);
        if (boardId != 0) m.put("board", boardId);
        if (owner != 0) m.put("own", owner);
        List<Object> icons = new ArrayList<>();
        for (Landmark landmark : landmarks) icons.add(landmark.toMap());
        m.put("lm", icons);
        if (!strokes.isEmpty()) {
            List<Object> rows = new ArrayList<>();
            for (Stroke stroke : strokes) rows.add(stroke.toMap());
            m.put("ink", rows);
        }
        if (!notes.isEmpty()) {
            List<Object> rows = new ArrayList<>();
            for (Note note : notes) rows.add(note.toMap());
            m.put("note", rows);
        }
        return m;
    }

    /** A map read back out of a save or off the wire, or {@code null}. */
    public static Chart fromMap(Map<String, Object> m) {
        long id = WatchJson.big(m, "id", 0);
        if (id == 0) return null;
        List<Landmark> icons = new ArrayList<>();
        for (Map<String, Object> row : WatchJson.objects(m, "lm")) {
            Landmark landmark = Landmark.fromMap(row);
            if (landmark != null) icons.add(landmark);
        }
        Chart chart = new Chart(id, WatchJson.str(m, "n", UNTITLED),
                WatchJson.num(m, "x", 0), WatchJson.num(m, "y", 0),
                WatchJson.num(m, "r", MIN_RADIUS), WatchJson.str(m, "by", null),
                WatchJson.big(m, "t", 0), icons);
        chart.setBoardId(WatchJson.big(m, "board", 0));
        chart.setOwner(WatchJson.integer(m, "own", 0));
        for (Map<String, Object> row : WatchJson.objects(m, "ink")) {
            chart.add(Stroke.fromMap(row));
        }
        for (Map<String, Object> row : WatchJson.objects(m, "note")) {
            chart.add(Note.fromMap(row));
        }
        return chart;
    }

    /** A coordinate, to the centimetre — {@code WatchProto.state}'s reasoning. */
    private static double round(double v) {
        return Math.round(v * 100) / 100.0;
    }

    /** A string cut to a length, without an ellipsis: this is a limit, not a label. */
    static String trim(String text, int limit) {
        String trimmed = text.trim();
        return trimmed.length() > limit ? trimmed.substring(0, limit) : trimmed;
    }

    @Override public String toString() {
        return name + " (" + Math.round(span()) + " m at " + Math.round(centreX) + ", "
                + Math.round(centreY) + ")";
    }
}
